# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Socoliuc.FollowFrame
PackageVersion: 0.3.13
InstallerType: portable
UpgradeBehavior: install
Commands:
- followframe
Installers:
- Architecture: x64
  InstallerUrl: https://followframe.com/downloads/FollowFrame-Single-Exe-0.3.13-win32-x64.exe
  InstallerSha256: 10C44E62350162FE56DAE3C04F48B15CE6B6C653ED584DE2EBAE641BABF37D2F
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-09
